### ISSUE TITLE
Default image (when not found)

### ISSUE THREAD

**Issue by ErenMustafaGit** [Siirko/symfoniya#46]
Put a default image when the image of the song is not found

![image](https://github.com/Siirko/symfoniya/assets/82711747/e3b52ab8-f485-43ee-8941-529a67317997)

**Comment by Siirko** [comment]
The grey color is already a default image 

https://github.com/Siirko/symfoniya/blob/8690687c65163886271e290bc0f45989a1d2187a/src/lib/utils.ts#L14

**Comment by Siirko** [comment]
![image](https://github.com/Siirko/symfoniya/assets/77932724/19e6ed07-1bc9-47b0-807c-4f80ab34ac98)
Will be updated to next v0.1.3
